name: dff-program-y-dangerous-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8022
      SERVICE_NAME: dff_program_y_dangerous_skill
    context: .
    dockerfile: ./skills/dff_program_y_dangerous_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8022 --reload
  deploy:
    resources:
      limits:
        memory: 1024M
      reservations:
        memory: 1024M
  volumes:
  - ./skills/dff_program_y_dangerous_skill:/src
  - ./common:/src/common
  ports:
  - 8022:8022
proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8022
  - PORT=8022
