FROM python:3.7-slim-stretch

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y --fix-missing && \
    apt-get install -y -q \
        build-essential \
        openssl \
        git \
        libssl-dev \
        libffi-dev \
        cron && \
    rm -rf /var/lib/apt/lists/*

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONPATH "${PYTHONPATH}:/dp-agent"
ENV DPA_LAUNCHING_ENV "docker"

RUN mkdir dp-agent
WORKDIR /dp-agent
# TODO: Copy only necessary dirs and files

RUN mkdir /pavlov && \
    cd /pavlov && \
    git clone https://github.com/deeppavlov/DeepPavlov && \
    cd DeepPavlov && \
    pip install -e .

RUN pip install sentry-sdk==0.16.0 requests==2.24.0 pandas GitPython==3.1.14 pyaml openpyxl==3.0.0 xlrd==1.2.0
RUN pip install pip install deeppavlov-agent==2.3.0a0

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONPATH "${PYTHONPATH}:/dp-agent"
ENV DPA_LAUNCHING_ENV "docker"

COPY . /dp-agent/.
#COPY agent_settings.py /usr/local/lib/python3.7/site-packages/deeppavlov_agent/settings.py
#RUN printf 'debug = False\nresponse_logger = False' > /dp-agent/dp_agent_settings.py


