FROM python:3.7-slim-stretch

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y --fix-missing && \
    apt-get install -y -q \
        build-essential \
        openssl \
        git \
        libssl-dev \
        libffi-dev \
        cron && \
    rm -rf /var/lib/apt/lists/*

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONPATH "${PYTHONPATH}:/dp-agent"
ENV DPA_LAUNCHING_ENV "docker"

RUN mkdir dp-agent
WORKDIR /dp-agent
# TODO: Copy only necessary dirs and files

# RUN pip install deeppavlov_agent==2.2.0 sentry-sdk==0.16.0 requests==2.24.0
RUN pip install sentry-sdk==0.16.0 requests==2.24.0 pandas
RUN pip install git+git://github.com/deepmipt/dp-agent.git@aab1bf88a6665d660106740c301758ca90214c8e

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONPATH "${PYTHONPATH}:/dp-agent"
ENV DPA_LAUNCHING_ENV "docker"

COPY . /dp-agent/.
#RUN printf 'debug = False\nresponse_logger = False' > /dp-agent/dp_agent_settings.py

# cronjobs
RUN mkdir /cron_env
COPY ./utils/agent_cronjobs /etc/cron.d/agent_cronjobs
RUN chmod 0644 /etc/cron.d/agent_cronjobs
RUN crontab /etc/cron.d/agent_cronjobs
RUN touch /var/log/cron.log

RUN pip install deeppavlov==0.13.0 pyaml openpyxl==3.0.0 xlrd==1.2.0
