FROM ubuntu:latest

RUN apt-get update -y --fix-missing && \
    apt-get install -y python3 python3-pip python3-dev build-essential git openssl

ENV PYTHONIOENCODING=utf-8

COPY requirements.txt /
RUN pip3 install -r requirements.txt

RUN mkdir dp-agent
WORKDIR /dp-agent
COPY . /dp-agent/.

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONPATH "${PYTONPATH}:/dp-agent"
ENV DPA_LAUNCHING_ENV "docker"

EXPOSE 4242