FROM ubuntu:latest

RUN apt-get update -y --fix-missing && \
    apt-get install -y python3 python3-pip python3-dev build-essential git openssl

RUN pip3 install deeppavlov tensorflow==1.10.0

RUN mkdir dp-agent
WORKDIR /dp-agent
COPY . /dp-agent/.
ENV PYTHONPATH "${PYTONPATH}:/dp-agent"

ARG skillconfig
ARG skillport
ARG skill_endpoint
ARG skillhost

ENV CONFIG=$skillconfig
ENV PORT=$skillport
ENV HOST=$skillhost
ENV ENDPOINT=$skill_endpoint

RUN python3 -m deeppavlov install $CONFIG
ENTRYPOINT python3 -m core.run_dp_servers $CONFIG -p $PORT -host $HOST -ep $ENDPOINT