FROM deeppavlov/base:latest

ARG skillconfig
ARG skillport
ARG skill_endpoint
ARG skillhost
ARG gpu

ENV CONFIG=$skillconfig
ENV PORT=$skillport
ENV HOST=$skillhost
ENV ENDPOINT=$skill_endpoint
ENV GPU=$gpu

RUN mkdir dp-agent
WORKDIR /dp-agent
COPY . /dp-agent/.
ENV PYTHONPATH "${PYTONPATH}:/dp-agent"

RUN if [ $GPU = "true" ]; then pip install -r /base/DeepPavlov/deeppavlov/requirements/tf-gpu.txt; fi
RUN python3 -m deeppavlov install $CONFIG
RUN python3 dp_server_config.py

RUN echo $CONFIG
ENTRYPOINT python3 -m deeppavlov riseapi $CONFIG -p $PORT -d
