services:
  agent:
    restart: unless-stopped
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
      - ".:/dp-agent"
    ports:
      - ${AGENT_PORT}:4242
  combined-classification:
    restart: unless-stopped
    environment:
      - CUDA_VISIBLE_DEVICES=7
  mongo:
    restart: unless-stopped
    command: mongod
    image: mongo:4.0.0
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  sentseg:
    restart: unless-stopped
  emotion-ranking-based-response-selector:
    restart: unless-stopped
  sentence-ranker:
    restart: unless-stopped
    environment:
      - CUDA_VISIBLE_DEVICES=9
version: '3.7'
