# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  ranking-based-response-selector:
    volumes:
      - "./response_selectors/ranking_based_response_selector:/src"
      - "./common:/src/common"
    ports:
      - 8002:8002
  combined-classification:
    volumes:
      - "./common:/src/common"
      - "./annotators/combined_classification:/src"
    ports:
      - 8087:8087
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8128:8128
  openai-api-chatgpt:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8145:8145
  openai-api-davinci3:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8131:8131
  openai-api-gpt4:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8159:8159
  openai-api-gpt4-32k:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8160:8160
  openai-api-chatgpt-16k:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8167:8167
  anthropic-api-claude-v1:
    volumes:
      - "./services/anthropic_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8164:8164
  anthropic-api-claude-instant-v1:
    volumes:
      - "./services/anthropic_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8163:8163
  dff-universal-prompted-skill:
    volumes:
      - "./skills/dff_universal_prompted_skill:/src"
      - "./common:/src/common"
    ports:
      - 8147:8147

version: "3.7"
