# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  convers-evaluator-annotator:
    volumes:
      - "./annotators/ConversationEvaluator:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8004:8004
  spacy-nounphrases:
    volumes:
      - "./annotators/spacy_nounphrases:/src"
      - "./common:/src/common"
    ports:
      - 8006:8006
  dff-program-y-skill:
    volumes:
      - "./skills/dff_program_y_skill:/src"
      - "./common:/src/common"
    ports:
      - 8008:8008
  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  convers-evaluation-selector:
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
      - "./common:/src/common"
    ports:
      - 8009:8009
  dff-intent-responder-skill:
    volumes:
      - "./skills/dff_intent_responder_skill:/src"
      - "./common:/src/common"
    ports:
      - 8012:8012
  dff-command-selector-skill:
    volumes:
      - "./skills/dff_command_selector_skill:/src"
      - "./common:/src/common"
    ports:
      - 8015:8015
  intent-catcher-commands:
    volumes:
      - "./annotators/IntentCatcherTransformers:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8014:8014
  badlisted-words:
    volumes:
      - "./annotators/BadlistedWordsDetector:/src"
      - "./common:/src/common"
    ports:
      - 8018:8018
  spelling-preprocessing:
    volumes:
      - "./annotators/spelling_preprocessing:/src"
    ports:
      - 8074:8074
  dialogpt:
    volumes:
      - "./services/dialogpt:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8125:8125
  entity-detection:
    volumes:
      - "./annotators/entity_detection:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8103:8103
  ner:
    volumes:
      - './annotators/NER:/src'
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8021:8021
  robot-command-sender:
    volumes:
      - "./services/robot_command_sender:/src"
      - "./common:/src/common"
    ports:
      - 8135:8135
  robot-notifications:
    volumes:
      - "./services/robot_notifications:/src"
      - "./common:/src/common"
    ports:
      - 8136:8136
  robot-fake-server:
    volumes:
      - "./services/robot_fake_server:/src"
      - "./common:/src/common"
    ports:
      - 8137:8137

version: "3.7"
