name: convers-evaluation-selector-ru
endpoints:
- respond
compose:
  env_file:
  - .env_ru
  build:
    args:
      TAG_BASED_SELECTION: 1
      CALL_BY_NAME_PROBABILITY: 0.5
      PROMPT_PROBA: 0.1
      ACKNOWLEDGEMENT_PROBA: 0.3
      PRIORITIZE_WITH_REQUIRED_ACT: 0
      PRIORITIZE_NO_DIALOG_BREAKDOWN: 0
      PRIORITIZE_WITH_SAME_TOPIC_ENTITY: 0
      IGNORE_DISLIKED_SKILLS: 0
      GREETING_FIRST: 1
      RESTRICTION_FOR_SENSITIVE_CASE: 1
      PRIORITIZE_PROMTS_WHEN_NO_SCRIPTS: 1
      MAX_TURNS_WITHOUT_SCRIPTS: 7
      ADD_ACKNOWLEDGMENTS_IF_POSSIBLE: 1
      PRIORITIZE_SCRIPTED_SKILLS: 0
      CONFIDENCE_STRENGTH: 0.8
      CONV_EVAL_STRENGTH: 0.4
      PRIORITIZE_HUMAN_INITIATIVE: 1
      QUESTION_TO_QUESTION_DOWNSCORE_COEF: 0.8
      LANGUAGE: RU
      FLASK_APP: server
    context: .
    dockerfile: ./response_selectors/convers_evaluation_based_selector/Dockerfile
  command: flask run -h 0.0.0.0 -p 8009
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
  volumes:
  - ./response_selectors/convers_evaluation_based_selector:/src
  - ./common:/src/common
  ports:
  - 8009:8009
proxy: null
