name: spacy-nounphrases
endpoints:
- respond
- respond_batch
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8006
      SERVICE_NAME: spacy_nounphrases
      FLASK_APP: server
    context: .
    dockerfile: ./annotators/spacy_nounphrases/Dockerfile
  command: flask run -h 0.0.0.0 -p 8006
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
  volumes:
  - ./annotators/spacy_nounphrases:/src
  - ./common:/src/common
  ports:
  - 8006:8006
proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8006
  - PORT=8006
