services:
  agent:
    restart: unless-stopped
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
      - ".:/dp-agent"
    ports:
      - ${AGENT_PORT}:4242
  combined-classification:
    restart: unless-stopped
    environment:
      - CUDA_VISIBLE_DEVICES=7
  mongo:
    restart: unless-stopped
    command: mongod
    image: mongo:4.0.0
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  sentseg:
    restart: unless-stopped
  convers-evaluation-selector:
    restart: unless-stopped
  badlisted-words:
    restart: unless-stopped
  ner:
    restart: unless-stopped
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=7
  entity-linking:
    restart: unless-stopped
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  spelling-preprocessing:
    restart: unless-stopped
  entity-detection:
    restart: unless-stopped
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=9
  convers-evaluator-annotator:
    restart: unless-stopped
    environment:
      - CUDA_VISIBLE_DEVICES=6
  transformers-lm-oasst12b:
    restart: unless-stopped
    environment:
      - CUDA_VISIBLE_DEVICES=0
  dff-template-skill:
    restart: unless-stopped
  property-extraction:
    restart: unless-stopped
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
version: '3.7'
