intent-catcher:
- group: annotators
  connector:
    protocol: http
    timeout: 1.0
    url: http://intent-catcher:8014/detect
  dialog_formatter: state_formatters.dp_formatters:last_utt_sentseg_segments_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.spelling_preprocessing
  - annotators.sentseg
  state_manager_method: add_annotation
intent-catcher-ru:
- group: annotators
  connector:
    protocol: http
    timeout: 1.0
    url: http://intent-catcher-ru:8014/detect
  dialog_formatter: state_formatters.dp_formatters:last_utt_sentseg_segments_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.spelling_preprocessing
  - annotators.sentseg
  state_manager_method: add_annotation
