FROM deeppavlov/base-gpu:0.6.1

ARG skillconfig
ARG skillport
ARG skill_endpoint
ARG skillhost

ENV CONFIG=$skillconfig
ENV PORT=$skillport
ENV HOST=$skillhost
ENV ENDPOINT=$skill_endpoint
ENV TFHUB_CACHE_DIR=/tmp/tfhub

VOLUME /tmp/tfhub

RUN mkdir dp-agent
WORKDIR /dp-agent
ENV PYTHONPATH "${PYTONPATH}:/dp-agent"

COPY $CONFIG /dp-agent/$CONFIG
RUN python -m deeppavlov download $CONFIG
RUN pip install -r /base/DeepPavlov/deeppavlov/requirements/tf-gpu.txt

COPY . /dp-agent/.

RUN python -m deeppavlov install $CONFIG
RUN python dp/dp_server_config.py
RUN sed -i "/uvicorn.run/s/app,/app, timeout_keep_alive=20,/g" "/base/DeepPavlov/deeppavlov/utils/server/server.py"

ENTRYPOINT python -m deeppavlov riseapi $CONFIG -p $PORT