FROM python:3.7.6

RUN apt-get update && apt-get install git -y

ARG CONFIG
ARG SRC_DIR
ARG COMMIT=0.13.0

ENV CONFIG=$CONFIG
ENV PORT=$PORT

ARG SED_ARG=" | "
ARG SERVICE_NAME
ENV SERVICE_NAME ${SERVICE_NAME}

COPY ./annotators/entity_detection/requirements.txt /src/requirements.txt
RUN pip install -r /src/requirements.txt

COPY $SRC_DIR /src
WORKDIR /src

RUN pip install git+https://github.com/deepmipt/DeepPavlov.git@${COMMIT}
RUN python -m deeppavlov install $CONFIG

ARG SERVICE_PORT
ENV SERVICE_PORT ${SERVICE_PORT}

RUN sed -i "s|$SED_ARG|g" "$CONFIG"

CMD gunicorn --workers=1 --timeout 300 server:app -b 0.0.0.0:${SERVICE_PORT}

