combined_classes = {  # ORDER MATTERS!!!! DO NOT CHANGE IT!!!!
    "emotion_classification": ["anger", "fear", "joy", "disgust", "sadness", "surprise", "neutral"],
    "sentiment_classification": ["positive", "neutral", "negative"],
    "toxic_classification": [
        "identity_hate",
        "insult",
        "obscene",
        "severe_toxic",
        "sexual_explicit",
        "threat",
        "toxic",
        "not_toxic",
    ],
    "factoid_classification": ["is_factoid", "is_conversational"],
    "midas_classification": [
        "open_question_factual",
        "open_question_opinion",
        "open_question_personal",
        "yes_no_question",
        "clarifying_question",
        "command",
        "dev_command",
        "appreciation",
        "opinion",
        "complaint",
        "comment",
        "statement",
        "other_answers",
        "pos_answer",
        "neg_answer",
    ],
    "deeppavlov_topics": [
        "Food",
        "Books&Literature",
        "Music",
        "Gadgets",
        "Movies&Tv",
        "Leisure",
        "Beauty",
        "Clothes",
        "Travel",
        "News",
        "Art&Hobbies",
        "Videogames",
        "Job",
        "Home&Design",
        "Depression",
        "Celebrities&Events",
        "Politics",
        "Toys&Games",
        "Animals&Pets",
        "PersonalTransport",
        "Garden",
        "Family&Relationships",
        "Health&Medicine",
        "Religion",
        "ArtificialIntelligence",
        "Finance",
        "Space",
        "Disasters",
        "Science&Technology",
        "Psychology",
        "MassTransit",
        "Education",
        "Sports",
    ],
    "cobot_topics": [
        "Phatic",
        "Other",
        "Movies_TV",
        "Music",
        "SciTech",
        "Literature",
        "Travel_Geo",
        "Celebrities",
        "Games",
        "Pets_Animals",
        "Sports",
        "Psychology",
        "Religion",
        "Weather_Time",
        "Food_Drink",
        "Politics",
        "Sex_Profanity",
        "Art_Event",
        "Math",
        "News",
        "Entertainment",
        "Fashion",
    ],
    "cobot_dialogact_topics": [
        "Other",
        "Phatic",
        "Entertainment_Movies",
        "Entertainment_Books",
        "Entertainment_General",
        "Interactive",
        "Entertainment_Music",
        "Science_and_Technology",
        "Sports",
        "Politics",
        "Inappropriate_Content",
    ],
    "cobot_dialogact_intents": [
        "Information_DeliveryIntent",
        "General_ChatIntent",
        "Information_RequestIntent",
        "User_InstructionIntent",
        "InteractiveIntent",
        "Opinion_ExpressionIntent",
        "OtherIntent",
        "ClarificationIntent",
        "Topic_SwitchIntent",
        "Opinion_RequestIntent",
        "Multiple_GoalsIntent",
    ],
    "topics_ru": [
        "музыка",
        "еда, напитки и кулинария",
        "новости",
        "транспорт",
        "погода",
        "медиа и коммуникации",
        "автомобили",
        "общественный транспорт",
        "литература",
        "чтение",
        "гаджеты",
        "смартфоны",
        "планшеты",
        "электроника",
        "кино",
        "сериалы",
        "тв",
        "телевидение",
        "красота и уход",
        "косметология",
        "одежда",
        "путешествия",
        "туризм",
        "искусство",
        "искусство и культура",
        "видеоигры",
        "работа",
        "карьера",
        "дом",
        "дизайн",
        "депрессия",
        "знаменитости",
        "политика",
        "игрушки",
        "настольные игры",
        "животные",
        "домашние животные",
        "садоводство",
        "растениеводство",
        "семья",
        "отношения",
        "медицина",
        "религия",
        "искусственный интеллект",
        "машинное обучение",
        "финансы",
        "космос",
        "стихийные бедствия",
        "наука",
        "технологии",
        "психология",
        "образование",
        "мода и стиль",
        "история",
        "налоги",
        "любовь",
        "война",
        "деньги",
        "физика",
        "иностранные языки",
        "юриспруденция",
        "самолёты",
        "покупки",
        "криминал",
        "кошки",
        "собаки",
        "философия",
        "бизнес и менеджмент",
        "математика",
        "предпринимательство",
        "спорт",
        "фитнес",
        "секспросвет",
        "феминизм",
        "секс",
        "еда",
    ],
}

TOPIC_GROUPS = {
    "food": ["Food", "Food_Drink", "еда, напитки и кулинария", "еда"],
    "books": ["Entertainment_Books", "Literature", "Books&Literature", "литература", "чтение"],
    "music": ["Music", "Entertainment_Music", "музыка"],
    "news": ["News", "новости"],
    "politics": ["Politics", "политика"],
    "sports": ["Sports", "спорт", "фитнес"],
    "religion": ["Religion"],
    "movies": ["Entertainment_Movies", "Movies_TV", "Movies&Tv", "сериалы", "тв", "телевидение"],
    "fashion": ["Clothes", "Fashion", "одежда", "мода и стиль"],
    "travel": ["Travel", "Travel_Geo", "путешествия", "туризм"],
    "celebrities": ["Celebrities", "Celebrities&Events", "знаменитости"],
    "art": ["Art_Event", "Art&Hobbies", "искусство"],
    "science": ["Science_and_Technology", "SciTech", "наука", "технологии"],
    "entertainment": ["Entertainment", "Entertainment_General"],
    "games": ["Games", "Toys&Games", "Videogames", "видеоигры", "игрушки", "настольные игры"],
    "animals": ["Pets_Animals", "Animals&Pets", "кошки", "собаки"],
    "sex": ["Sex_Profanity", "секс", "секспросвет"],
    "weather": ["Weather_Time", "погода"],
}  # The list can be expanded according to the topic list supported
