import re

HOBBIES_RE = re.compile(
    r"\b(Acroyoga|Acting|Aerial silk|Airbrushing|Amateur radio"
    "|Animation|Aquascaping|Art|Astrology|Babysitting|Baking"
    "|Basketball|Baton twirling|Beatboxing|Beer sommelier"
    "|Beer tasting|Binge-watching|Blogging|Board game|Board games"
    "|Book discussion club|Book restoration|Bowling|Brazilian jiu-jitsu|"
    "Breadmaking|Building|Bullet Journal|Bullet journaling|Calligraphy"
    "|Candle making|Candy making|Car|Car fixing|Card games|Cardistry"
    "|Ceramics|Online chat|Chat|Cheesemaking|Chess|Cleaning|Clothing"
    "|Clothesmaking|Home roasting coffee|Coffee roasting|Collecting"
    "|Coloring book|Coloring|Communication|Community activism|Computer programming"
    "|Confectionery|Construction|Cooking|Cosplaying|Couch surfing|Couponing|Craft"
    "|Creative writing|Crocheting|Cross-stitch|Crossword puzzles|Cryptography"
    "|Cue sports|Dance|Decorative arts|Decorating|Digital art|Dining|Diorama"
    "|Distro-hopping|Distro Hopping|Diving|Djembe|Disc-jockey|DJing|Do it yourself"
    "|Drama|Drawing|Mixed drink|Drink mixing|Drinking|Electronic games|Electronics"
    "|Embroidery|Engraving|Entertaining|Experimenting|Fantasy sport|Fashion"
    "|Fashion design|Feng shui|Feng shui decorating|Filmmaking|Fingerpainting"
    "|Fishfarming|Fishkeeping|Flower arranging|Fly tying|Second-language acquisition"
    "|Foreign language learning|Furniture|Furniture building|Games|Gaming|Genealogy"
    "|Gingerbread house|Gingerbread house making|Giving advice|Glassblowing|Gardening"
    "|Gongfu tea|Graphic design|Gunsmithing|Gymnastics|Hacker|Hacking|Computer hardware"
    "|Hardware|Herpetoculture|Herp keeping|Home improvement|Homebrewing|Houseplant care"
    "|Hula hooping|Humor|Hydroponics|Ice skating|Invention|Inventing|Jewelry making"
    "|Jigsaw puzzle|Diary|Journaling|Juggling|Karaoke|Karate|Kendama|Knife making|Knitting"
    "|Knot tying|Kombucha|Kombucha brewing|Kung fu|Lace making|Lapidary|Leather crafting"
    "|Lego|Lego building|Livestreaming|Music|Listening to music|Podcasts"
    "|Listening to podcasts|Lock picking|Machining|Macrame|Magic (illusion)|Magic"
    "|Makeup|Massaging|Maze|Mechanics|Meditation|Memory training|Metalworking"
    "|Miniature art|Simple living|Minimalism|Model building|Model engineering"
    "|Music|Nail art|Needlepoint|Origami|Painting|Palmistry|Performance|Pet|"
    "Pet adoption|Pet fostering|Pet sitting|Philately|Photography|Pilates|Planning"
    "|Plastic art|Music|Playing musical instruments|Poetry|Poi|Pole dancing|Postcrossing"
    "|Pottery|Powerlifting|Practical jokes|Pressed flower craft|Proofreading|Proofreading"
    "|Proverbs|Public speaking|Puppetry|Puzzle|Pyrography|Quilling|Quilting|Quizzes"
    "|Radio-controlled model|Radio-controlled model playing|Rail transport modeling|Rapping"
    "|Reading|Recipe|Recipe creation|Refinishing|Reiki|Gadget|Reviewing Gadgets|Robot combat|"
    "Rubik|Scrapbooking|Scuba Diving|Sculpting|Sewing|Shoemaking|Singing|Sketch"
    "|Skipping rope|Slot car|Soapmaking|Social media|Spreadsheets|Stamp collecting"
    "|Stand-up comedy|Storytelling|Striptease|Stripping|Sudoku|Table tennis"
    "|Talking|Tapestry|Tarot|Tatebanko|Tattoo|Tattooing|Taxidermy|joke|Telling jokes"
    "|Charity shop|Thrifting|Upcycling|Video editing|Video game development"
    "|Video game developing|Video gaming|Videography|Video making|Virtual Reality"
    "|VR Gaming|Wargaming|Watchmaker|Watch making|Documentary film|Watching documentaries"
    "|Movies|Watching movies|Television program|Watching television|Sealing wax|Wax sealing"
    "|Waxing|Weaving|Webtoon|Weight training|Welding|Whisky|Whittling|Wikipedia editing"
    "|Wine tasting|Winemaking|Witchcraft|Wood carving|Woodworking|Word searches"
    "|Worldbuilding|Writing|Musical composition|Writing music|Yo-yoing|Yoga|Zumba"
    "|Air sports|Airsoft|Amateur geology|Amusement park|Amusement park visiting|Archery"
    "|Auto detailing|Automobilism|Astronomy|Backpacking|Badminton|BASE jumping|Baseball"
    "|Basketball|Beachcombing|Beekeeping|Birdwatching|Blacksmithing|BMX|Board sports"
    "|Bodybuilding|Bonsai|Butterfly watching|Bus|Bus riding|Camping|Canoeing|Canyoning"
    "|Car|Car riding|Car tuning|Caving|City tourism|City trip|Climbing|Composting"
    "|Cycling|Dandy|Dandyism|Dog training|Dog walking|Dowsing|Driving|Farming"
    "|Fishing|Flag football|Flower|Flower growing|Aviation|Flying|Flying disc"
    "|Model aircraft|Flying model planes|Foraging|Fossicking|Freestyle football"
    "|Fruit picking|Gardening|Geocaching|Ghost hunting|Gold prospecting|Graffiti"
    "|Groundhopping|Guerrilla gardening|Handball|Herbalism|Herping|High-power rocketry"
    "|Hiking|Hobby horse|Hobby horsing|Hobby tunneling|Hooping|Horseback riding"
    "|Hunting|Inline skating|Jogging|Jumping rope|Karting|Kayaking|Kite|Kite flying"
    "|Kitesurfing|Lacrosse|LARPing|Letterboxing|Lomography|Longboarding|Martial arts"
    "|Metal detector|Metal detecting|Motorcycling|Meteorology|Motor sports|Mountain biking"
    "|Mountaineering|Museum|Museum visiting|Mushroom hunting|Netball|Noodling"
    "|Nordic skating|Orienteering|Paintball|Paragliding|Parkour|Photography|Picnicking"
    "|Podcast|Podcast hosting|Polo|Public transport|Public transport riding|Qigong"
    "|Radio-controlled model|Radio-controlled model playing|Rafting|Railway|Railway journeys"
    "|Rappelling|Renaissance fair|Renovating|Road Cycling|Road biking|Rock climbing"
    "|Rock art|Rock painting|Roller skating|Rugby football|Rugby|Running|Sailing"
    "|Sand art|Scouting|Scuba diving|Sculling|Shooting|Shopping|Shuffleboard"
    "|Skateboarding|Skiing|Skimboarding|Skydiving|Slacklining|sled|Sledding|Snorkeling"
    "|Snowboarding|Snowmobiling|Snowshoeing|Soccer|Stone skipping|Storm chasing|Sun bathing"
    "|Surfing|Survivalism|Human swimming|Swimming|Taekwondo|Tai chi|Tennis"
    "|Thru-hiking|Topiary|Tourism|Trade fair|Trade fair visiting|Travel|Unicycle"
    "|Unicycling|Urban exploration|Vacation|Vegetable farming|Vehicle restoration"
    "|Videography|Volunteering|Walking|Water sports|Zoo|Zoo visiting)\b",
    re.IGNORECASE,
)
