from common.universal_templates import ART_TEMPLATE, CHILL_TEMPLATE, SLEEP_TEMPLATE, SCHOOL_TEMPLATE, WORK_TEMPLATE

topic_config = \
    {"art":
     {"linkto": ["Would you like to talk about art?"],
      "pattern": ART_TEMPLATE,
      "expected_subtopic_info": [{"subtopic": "drawing", "cond": [[{"pattern": "draw|paint"}, "user", True]]},
                                 {"subtopic": "photo", "cond": [[{"pattern": "photo"}, "user", True]]}],
      "smalltalk": [{"utt": ["Drawing gives you a mean to self-reflect and externalize your emotions.",
                             "Do you like drawing?"],
                     "expected_subtopic_info": [{"subtopic": "drawing", "cond": [["is_yes", "user", True]]}]},
                    {"utt": ["In our increasingly busy lives it’s difficult to always be in the moment.",
                             "Taking pictures helps you to hang on to those memories a little longer.",
                             "Do you like taking photographs?"],
                     "expected_subtopic_info": [{"subtopic": "photo", "cond": [["is_yes", "user", True]]}]},
                    {"utt": ["Memes are funny artworks we can see on the Internet.", "Do you like memes?"],
                     "expected_subtopic_info": [{"subtopic": "memes", "cond": [["is_yes", "user", True]]}]},
                    {"utt": ["Do you draw with a pencil or with oil paints?"],
                     "subtopic": "drawing"},
                    {"utt": [
                        "What king of paintings do you like to draw: landscapes, portraits or something else?"],
                        "subtopic": "drawing"},
                    {"utt": ["Would you like to know how to improve your drawing skills?"],
                     "subtopic": "drawing",
                     "facts": [
                         {"wikihow_page": "Improve-Your-Drawing-Skills", "cond": [["is_yes", "user", True]]}]},
                    {"utt": ["In my town there is a lot of graffiti on walls.",
                             "What do you think about painting graffiti?"],
                     "subtopic": "drawing"},
                    {"utt": ["I like Shishkin paintings.", "Pictures of what painters do you like?"],
                     "subtopic": "drawing",
                     "expected_entities": [{"name": "user_fav_painter", "wiki_parser_types": ["Q1028181"]}]},
                    {"utt": ["I also like paintings of {user_fav_painter}!",
                             "Last weekend I was in National Gallery.", "Do you like to visit art museums?"],
                     "subtopic": "drawing"},
                    {"utt": ["Do you have any funny photos of your family or pets?"],
                     "subtopic": "photo"},
                    {"utt": ["I can tell you some tips about photography.",
                             "Would you like to know how to take picture of pets?"],
                     "subtopic": "photo",
                     "facts": [{"wikihow_page": "Photograph-Pets", "cond": [["is_yes", "user", True]]}]},
                    {"utt": ["Do you think that CIA watch you through the front-camera of your cell phone?"],
                     "subtopic": "photo"},
                    {"utt": ["Do you take photos on an SLR camera or on your cell phone?"],
                     "subtopic": "photo"},
                    {"utt": ["Do you share your photos in Instagram or Flickr?"],
                     "subtopic": "photo"},
                    {"utt": ["Using Photoshop or Adobe Lightroom can help to increase the quality of pictures.",
                             "Do you use any tools for photo processing?"],
                     "subtopic": "photo"},
                    {"utt": ["Do you think that memes are a separate kind of art, the same as painting?"],
                     "subtopic": "memes"},
                    {"utt": ["I draw some memes with cats.", "Have you tried to draw a meme?"],
                     "subtopic": "memes"},
                    {"utt": ["Would you like to know how to draw a meme?"],
                     "subtopic": "memes",
                     "facts": [{"wikihow_page": "Make-a-Meme", "cond": [["is_yes", "user", True]]}]}
                    ],
      "questions": [{"pattern": "(do|did) you (like|enjoy) (drawing|painting)",
                     "answer": "Yes, I like drawing."}
                    ],
      "triggers": {"entity_substr": [{"substr": [], "wikipedia_page": "", "wikihow_page": ""}],
                   "entity_types": ["Q1028181"]}
      },
     "chill":
     {"switch_on": [{"cond": [[[{"pattern": "what do you do on weekdays"}, "bot", True],
                               [{"pattern": CHILL_TEMPLATE}, "user", True]]],
                     "can_continue": "must", "conf": 1.0}],
      "pattern": CHILL_TEMPLATE,
      "smalltalk": [{"utt": ["Cool! I'm happy that you are having a great day!",
                             "Are you listening to music or playing games?"],
                     "expected_subtopic_info": [
                         {"subtopic": "music", "cond": [[{"pattern": "\\bmusic"}, "user", True]]},
                         {"subtopic": "play_with_friends",
                          "cond": [[{"pattern": "play with (my )?friends"}, "user", True]]}]},
                    {"utt": ["Music is a good way to relax.",
                             "Do you listen music in headphones or on a portable speaker?"],
                     "subtopic": "music",
                     "can_continue": "must", "conf": 1.0},
                    {"utt": ["I like Peter Helland music, it's very relaxing. What music do you like?"],
                     "subtopic": "music"},
                    {"utt": ["Yesterday my friend had a great fun jumping on a trampoline.",
                             "Do you like to jump on a trampoline?"],
                     "subtopic": "play_with_friends"},
                    {"utt": ["Do you play sports or games on your PC or console?"],
                     "subtopic": "play_with_friends"}
                    ]
      },
     "sleep":
     {"switch_on": [{"cond": [[[{"pattern": "what do you do on weekdays"}, "bot", True],
                               [{"pattern": SLEEP_TEMPLATE}, "user", True]]],
                     "can_continue": "must", "conf": 1.0}],
      "pattern": SLEEP_TEMPLATE,
      "smalltalk": [{"utt": ["Yes, it's time to relax after a hard day.",
                             "I can tell you what music you can listen to have a good sleep, shall I continue?"],
                     "expected_subtopic_info": [{"subtopic": "tell_about_music",
                                                 "cond": [["is_yes", "user", True],
                                                          [{"pattern": "(ok|tell me|yup)"}, "user", True]]}]},
                    {"utt": ["You can listen to sound of nature, for example birdsong or the sounds of sea.",
                             "Do you like sounds of the rain?"],
                     "subtopic": "tell_about_music"},
                    {"utt": ["There are a lot of compilations of relaxing music on Youtube.",
                             "I like Peter Helland music, it is very chilling. What music do you like?"],
                     "subtopic": "tell_about_music"}
                    ]
      },
     "play_with_friends":
     {"switch_on": [{"cond": [[[{"pattern": "what do you do on weekdays"}, "bot", True],
                               [{"pattern": "play with (my )?friends"}, "user", True]]],
                     "can_continue": "must", "conf": 1.0}],
      "pattern": "play with (my )?friends",
      "smalltalk": [{"utt": ["Yesterday my friend had a great fun jumping on a trampoline.",
                             "Do you like to jump on a trampoline?"]},
                    {"utt": ["Do you play sports or games on your PC or console?"]}]
      },
     "school":
     {"switch_on": [{"cond": [[[{"pattern": "what do you do on weekdays"}, "bot", True],
                               [{"pattern": SCHOOL_TEMPLATE}, "user", True]]],
                     "can_continue": "must", "conf": 1.0}],
      "pattern": SCHOOL_TEMPLATE,
      "smalltalk": [{"utt": ["My favourite subject is English, this language helps me to talk to a lot of people.",
                             "What is your favourite subject at school?"]},
                    {"utt": ["Yes, it's a very interesting subject.", "I believe you are a smart person.",
                             "I can tell you about some funny school pranks on teacher and classmates, "
                             "should I continue?"],
                     "expected_subtopic_info": [{"subtopic": "pranks", "cond": [["is_yes", "user", True]]}]
                     },
                    {"utt": ["Put chewing gum under the teachers coffee cup.", "Have you tried this trick?"],
                     "subtopic": "pranks"},
                    {"utt": ["One more prank: hide pieces of chalk inside the blackboard eraser so that it draws "
                             "lines when the teacher is trying to rub them out.",
                             "Have you played any jokes on your classmates?"],
                     "subtopic": "pranks"},
                    {"utt": ["Recently I have seen a cool movie You Goehte about adventures of children during "
                             "school year.",
                             "Have you seen this film?"]},
                    {"utt": ["Sport is a good way to relax after school.",
                             "Do you play on any of the school's sports teams?"],
                     "expected_subtopic_info": [{"subtopic": "sport_yes",
                                                 "cond": [["is_yes", "user", True],
                                                          [{"pattern": "used to"}, "user", True]]},
                                                {"subtopic": "sport_no", "cond": [["any"]]}],
                     "ackn": [{"cond": [[[{"pattern": "have you seen this film"}, "bot", True],
                                         ["is_yes", "user", True]]],
                               "answer": "Cool, i like this film too!"},
                              {"cond": [[[{"pattern": "have you seen this film"}, "bot", True],
                                         ["is_no", "user", True]]],
                               "answer": "I suggest you see, there are many funny moments in the film."}]
                     },
                    {"utt": ["What kind of sport do you play?"],
                     "subtopic": "sport_yes"},
                    {"utt": ["Anyway, I'd love to but I can't.",
                             "I believe you put all your resources to study well!"],
                     "subtopic": "sport_no"}
                    ]
      },
     "work":
     {"switch_on": [{"cond": [[[{"pattern": "what do you do on weekdays"}, "bot", True],
                               [{"pattern": WORK_TEMPLATE}, "user", True]]],
                     "can_continue": "must", "conf": 1.0}],
      "pattern": WORK_TEMPLATE,
      "smalltalk": [{"utt": ["I also have a work. It is to chat with people all day long.",
                             "So, I'm a professional talker.",
                             "What is your current occupation?"]},
                    {"utt": ["I think you do a very important and useful work!",
                             "I'm very curious what a typical day at your current job is like?"]},
                    {"utt": ["Ok, that's very interesting.",
                             "Do you think it is more important to make a lot of money than to enjoy your job?"],
                     "expected_subtopic_info": [{"subtopic": "money_yes", "cond": [["is_yes", "user", True]]},
                                                {"subtopic": "money_no", "cond": [["any"]]}]},
                    {"utt": ["So agree with you!", "Money is a terrible master but an excellent servant.",
                             "Do you agree?"],
                     "subtopic": "money_yes"},
                    {"utt": ["I definitely agree with you!",
                             "Benjamin Franklin once said: Money never made a man happy yet, nor will it.",
                             "Do you agree?"],
                     "subtopic": "money_no"},
                    {"utt": ["What is your favourite way to relax after work?",
                             "Do you have a hobby that you really enjoy?"]},
                    {"utt": ["It's a great pleasure to learn new sides of your personality. Thanks for sharing!"]}
                    ]
      },
     "harry_potter":
     {"switch_on": [{"cond": [[{"pattern": "harry potter"}, "user", True]], "can_continue": "must", "conf": 1.0}],
      "smalltalk": [{"utt": ["Harry Potter is an amazing novel which takes you to the magic world.",
                             "Which of the main characters do you like most: Harry, Ron or Herminone?"]},
                    {"utt": ["Do you think that using magic outside of Hogwarts is fine?"]},
                    {"utt": ["I can talk to you in Parseltongue, the language of snakes, should I continue?"],
                     "expected_subtopic_info": [{"subtopic": "parseltongue", "cond": [["is_yes", "user", True]]}]},
                    {"utt": ["I can tell you how to make a potion which Professor Snape made in his lab, "
                             "should I continue?"],
                     "expected_subtopic_info": [{"subtopic": "potion", "cond": [["is_no", "user", False]]}]},
                    {"utt": ["I like Harry Potter and the Philosopher's Stone.",
                             "Which of the series do you like?"],
                     "expected_subtopic_info": [{"subtopic": "philosopher_stone",
                                                 "cond": [[{"pattern": "(philosopher|stone)"}, "user", True]]},
                                                {"subtopic": "chamber_of_secrets",
                                                 "cond": [[{"pattern": "(chamber|secrets)"}, "user", True]]},
                                                {"subtopic": "prisoner_of_azkaban",
                                                 "cond": [[{"pattern": "(prisoner|azbakan)"}, "user", True]]},
                                                {"subtopic": "goblet_of_fire",
                                                 "cond": [[{"pattern": "(goblet|fire)"}]]},
                                                {"subtopic": "order_phoenix",
                                                 "cond": [[{"pattern": "(order|phoenix)"}, "user", True]]},
                                                {"subtopic": "half_blood_prince",
                                                 "cond": [[{"pattern": "(blood|prince)"}, "user", True]]},
                                                {"subtopic": "deathly_hallows",
                                                 "cond": [[{"pattern": "(deathly|hallow)"}, "user", True]]}
                                                ]},
                    {"utt": ["Philosopher's Stone is very breathtaking!",
                             "In this part Harry Potter begins to study at Hogwarts "
                             "and faces a lot of adventures."],
                     "subtopic": "philosopher_stone"},
                    {"utt": ["Chamber of Secrets keeps in suspense.",
                             "My favourite moment was the battle of Harry with Basilisk.",
                             "What scene do you like most?"],
                     "subtopic": "chamber_of_secrets",
                     "can_continue": "must", "conf": 1.0},
                    {"utt": ["Prisoner of Azkaban's plot has quite a suprise development.",
                             "Sirius Black has been wrongly convicted."],
                     "subtopic": "prisoner_of_azbakan",
                     "can_continue": "must", "conf": 1.0},
                    {"utt": ["My favourite moment in Goblet of Fire is Harry's battle with Voldemort."],
                     "subtopic": "goblet_of_fire",
                     "can_continue": "must", "conf": 1.0},
                    {"utt": ["I like Harry Potter and the Order of the Phoenix.",
                             "What is your favourite moment in the film?"],
                     "subtopic": "order_phoenix",
                     "can_continue": "must", "conf": 1.0},
                    {"utt": ["I also like Half-Blood Prince series.",
                             "Would you like to have Felix Felicis or Liquid Luck potion "
                             "which could make you lucky for a period of time?"],
                     "subtopic": "half_blood_prince",
                     "can_continue": "must", "conf": 1.0},
                    {"utt": ["In Deathly Hallows Harry finally defeated Voldemort.",
                             "What scene do you like most?"],
                     "subtopic": "deathly_hallows",
                     "can_continue": "must", "conf": 1.0},
                    {"utt": ["ai gife apsle. dofe dinfe feslure.",
                             "In Elglish it means I eat an apple. A dog jumped on the floor."],
                     "subtopic": "parseltongue"},
                    {"utt": ["To make magical, fizzy potions all you need to do is mix a combination of coloured "
                             "water, vinegar and baking soda in a container."],
                     "subtopic": "potion"},
                    {"utt": ["Materials for the potion: Red Cabbage, Water, Containers, Bicarbonate of Soda, Lemon "
                             "Juice and Vinegar."],
                     "subtopic": "potion"},
                    {"utt": ["I think that quidditch is a very spectacular type of sport.",
                             "Do you think that quidditch rules are similar to football, "
                             "except for that players do not run but fly on brromsticks?"]},
                    {"utt": ["Harry Potter had an owl who brought him letters.",
                             "Would you like to have a pet owl?"]}
                    ],
      "ackn": [{"cond": [[[{"pattern": "which of the main characters do you like most"}, "bot", True],
                          [{"pattern": "harry"}, "user", True]]],
                "answer": ["Yes, I like Harry, is was fun to watch his adventures."]},
               {"cond": [[[{"pattern": "which of the main characters do you like most"}, "bot", True],
                          [{"pattern": "ron"}, "user", True]]],
                "answer": ["Yes, I like Ron, he is Harry's friend and helps him a lot."]},
               {"cond": [[[{"pattern": "which of the main characters do you like most"}, "bot", True],
                          [{"pattern": "hermione"}, "user", True]]],
                "answer": ["Yes, I like Hermione. After Harry and Ron save her from a mountain troll in the "
                           "girls' restroom, she becomes best friends with them and often uses her quick wit, deft "
                           "recall, and encyclopaedic knowledge to lend aid in dire situations."]},
               {"cond": [[[{"pattern": "pet owl"}, "bot", True], ["is_yes", "user", True]]],
                "answer": ["I think that if I had an owl, she may hoot at night and disturb my sleep."]},
               {"cond": [[[{"pattern": "magic outside hogwarts"}, "bot", True], ["is_yes", "user", True]]],
                "answer": ["I definitely agree with you!"]},
               {"cond": [[[{"pattern": "magic outside hogwarts"}, "bot", True], ["is_no", "user", True]]],
                "answer": ["I definitely agree with you!"]}
               ]
      }
     }
