name: dff-wiki-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8111
      SERVICE_NAME: dff_wiki_skill
      COMMIT: 5b99ac3392e8e178e2bb4f9b218d4ddb2ec2e242
    context: ./
    dockerfile: ./skills/dff_wiki_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8111
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
  volumes:
  - ./skills/dff_wiki_skill:/src
  - ./common:/src/common
  ports:
  - 8111:8111
proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8111
  - PORT=8111
