services:

  sentseg:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=proxy.deeppavlov.ai:8011
      - PORT=8011

  combined-classification:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=proxy.deeppavlov.ai:8087
      - PORT=8087

  sentence-ranker:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=proxy.deeppavlov.ai:8128
      - PORT=8128

  transformers-lm-vicuna13b:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=proxy.deeppavlov.ai:8168
      - PORT=8168

version: '3.7'
