{
 "title": "Metrics",
 "tags": [ "metrics" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": "label_values(kubernetes_namespace)"
   },
   {
    "name": "app",
    "query": "label_values(up{container_name=\"alexaservice\", kubernetes_namespace=\"$env\"}, kubernetes_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "request latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_requests_latency_seconds_bucket{kubernetes_name=\"$app\", kubernetes_namespace=\"$env\"}[5m])) by (le, endpoint))",
     "legendFormat": "endpoint={{endpoint}}"
    }
   ]
  },
  {
   "title": "rps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_count_total{kubernetes_name=\"$app\", kubernetes_namespace=\"$env\"}[5m])) by (endpoint)",
     "legendFormat": "endpoint={{endpoint}}"
    }
   ]
  },
  {
   "title": "requests inflight",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{kubernetes_name=\"$app\", kubernetes_namespace=\"$env\"}) by (endpoint)",
     "legendFormat": "endpoint={{endpoint}}"
    }
   ]
  },
  {
   "title": "error rps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_count_total{kubernetes_name=\"$app\",kubernetes_namespace=\"$env\",code!~\"2..\"}[5m])) by (status_code,endpoint)",
     "legendFormat": "endpoint={{endpoint}}, code={{status_code}}"
    }
   ]
  }
 ]
}